logging:
  level:
    pl.luk: INFO
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
